# Generated by Django 5.2.9 on 2025-12-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debit',
            name='emi_type',
            field=models.CharField(choices=[('NO', 'No'), ('SHORT_TERM', 'Short_term'), ('LONG_TERM', 'Long_term'), ('CUSTOM', 'Custom')], default='NO', max_length=20),
        ),
    ]
