# Generated by Django 5.2.9 on 2025-12-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debit', '0002_alter_debit_emi_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='debit',
            name='last_emi_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
