# Generated by Django 5.2.9 on 2025-12-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('RENT', 'House Rent'), ('HOUSE_EXP', 'House Expenses'), ('INTERNET', 'Internet / WiFi'), ('MOBILE', 'Mobile Recharge / Bill'), ('GROCERIES', 'Groceries'), ('FOOD', 'Food'), ('VEHICLE', 'Vehicle'), ('MEDICAL', 'Medical Expenses'), ('HEALTH_INSURANCE', 'Health Insurance'), ('EDUCATION', 'Education'), ('CLOTHING', 'Clothing'), ('FOOTWEAR', 'Footwear'), ('MOVIE', 'Movies'), ('ONLINE_SHOPPING', 'Online Shopping'), ('CREDIT_CARD', 'Credit Card Payment'), ('BANK_CHARGES', 'Bank Charges'), ('GIFT', 'Gift'), ('DONATION', 'Donation'), ('TRAVEL', 'Travel / Trip'), ('OTHERS', 'Others')], max_length=100),
        ),
    ]
