# Generated by Django 5.2.9 on 2025-12-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_incomecategory_alter_income_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('GIFT', 'Gift'), ('SALARY', 'Salary'), ('OTHERS', 'Others')], max_length=20),
        ),
        migrations.DeleteModel(
            name='IncomeCategory',
        ),
    ]
