# Generated by Django 5.2.9 on 2025-12-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_alter_income_category_delete_incomecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('SALARY', 'Salary'), ('BONUS', 'Bonus'), ('COMMISSION', 'Commission'), ('FREELANCE', 'Freelance / Contract'), ('BUSINESS', 'Business Income'), ('CONSULTING', 'Consulting'), ('PROFIT', 'Business Profit'), ('INTEREST', 'Interest'), ('RENTAL', 'Rental Income'), ('CAPITAL_GAIN', 'Capital Gain'), ('GIFT', 'Gift'), ('DONATION', 'Donation Received'), ('REFUND', 'Refund'), ('CASHBACK', 'Cashback'), ('PRIZE', 'Prize / Lottery'), ('PENSION', 'Pension'), ('SUBSIDY', 'Government Subsidy'), ('SCHOLARSHIP', 'Scholarship'), ('YOUTUBE', 'YouTube Income'), ('BLOG', 'Blog / Content'), ('ONLINE_SALES', 'Online Sales'), ('OTHERS', 'Others')], max_length=20),
        ),
    ]
