# Generated by Django 5.2.9 on 2025-12-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emi',
            name='reminder_5_days_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emi',
            name='reminder_due_day_sent',
            field=models.BooleanField(default=False),
        ),
    ]
