# Generated by Django 5.2.9 on 2025-12-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emi', '0002_emi_reminder_5_days_sent_emi_reminder_due_day_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='emi',
            name='last_emi_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
