# Generated by Django 5.2.9 on 2025-12-21 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emi', '0003_emi_last_emi_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emi',
            name='last_emi_amount',
        ),
    ]
